### ISSUE TITLE
Breaking change on CallContext parameters in version 1.9.0?

### ISSUE THREAD

**Issue by Preben-EWE** [max-ieremenko/ServiceModel.Grpc#282]
Hi,

We are passing on some custom meta data in our gRPC services via the CallContext. This works fine in version 1.8.3 but when upgrading to 1.9.0 we get an ArgumentOutOfRangeException for these methods (see stack trace below). Any known changes regarding this (maybe an updated way of passing call context along)? 

I could not deduce a reason for this from the changelog but the split of ServiceModel.Grpc seems pretty fundamental.

Part of our service:
```
[ServiceContract]
public interface IConfigDataRepository
{
    [OperationContract]
    Task<List<ConfigDto>> GetConfig(CallContext? context);
}
```

Stack track of the error when calling a method like ```GetConfig()```:
```
lvl=ERR  Default exception handler activated.
 System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'CallOptionsBuilder does not implement method WithObject.')
   at ServiceModel.Grpc.Emit.ReflectionTools.InstanceMethod(Type type, String name)
   at ServiceModel.Grpc.Emit.CodeGenerators.EmitClientBuilder.InitializeCallOptionsBuilder(ILGenerator body, OperationDescription`1 operation)
   at ServiceModel.Grpc.Emit.CodeGenerators.EmitClientBuilder.BuildUnary(ILGenerator body, OperationDescription`1 operation, String grpcMethodName)
   at ServiceModel.Grpc.Emit.CodeGenerators.EmitClientBuilder.ImplementMethod(OperationDescription`1 operation, String grpcMethodName)
   at ServiceModel.Grpc.Emit.CodeGenerators.EmitClientBuilder.Build(ModuleBuilder moduleBuilder)
   at ServiceModel.Grpc.Emit.EmitGenerator.GenerateClientBuilder[TContract](ILogger logger)
   at ServiceModel.Grpc.Client.ClientRegistration.EmitBuilder[TContract](ILogger logger)
   at ServiceModel.Grpc.Client.ClientRegistration.Build[TContract](IClientBuilder`1 builder, ServiceModelGrpcClientOptions defaultOptions, Action`1 configure)
   at ServiceModel.Grpc.Client.ClientFactory.RegisterClient[TContract](IClientBuilder`1 userBuilder, Action`1 configure, Boolean ignoreDuplication)
   at ServiceModel.Grpc.Client.ClientFactory.CreateClient[TContract](CallInvoker callInvoker)
   at ServiceModel.Grpc.Client.DependencyInjection.Internal.ClientResolver`1.Resolve(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebAppFrontend.Middleware.LogUsernameMiddleware.InvokeAsync(HttpContext context, IServiceProvider serviceProvider) in C:\Users\pfh\source\repos\ewe-development\rina-frontend\WebAppFrontend\Middleware\LogUsernameMiddleware.cs:line 41
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by max-ieremenko** [comment]
Hi @Preben-EWE,

> Task<List<ConfigDto>> GetConfig(CallContext? context);
>
> Parameter 'CallOptionsBuilder does not implement method WithObject.'

The exception message states that the type of parameter `context ` was recognized as an `object type`.

```c#
[ServiceContract]
public interface IConfigDataRepository
{
    // this works
    [OperationContract]
    Task<List<ConfigDto>> GetConfig(CallContext? context);

   // this does not => ArgumentOutOfRangeException
    [OperationContract]
    Task<List<ConfigDto>> GetConfigFail(object? context);
}
```

It seems somewhere in your contracts there is a parameter(s) with type `object`.

**Comment by Preben-EWE** [comment]
Yes, we did have a contract with an `object` parameter. I did not suspect the service definitions since it was working in v1.8.3 but we back on the newest version.

Thanks a lot.
